apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-turkan-clinic
  labels:
    app: dr-turkan-clinic
network:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dr-turkan-clinic
  template:
    metadata:
      labels:
        app: dr-turkan-clinic
    spec:
      containers:
      - name: web-app
        image: gcr.io/YOUR_PROJECT_ID/dr-turkan-clinic:latest # The pipeline usually overwrites this dynamically
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dr-turkan-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dr-turkan-clinic
